### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by mre** [robclu/leapfrog#1]
[Dashmap](https://github.com/xacrimon/dashmap) supports [serde](https://github.com/xacrimon/dashmap/blob/master/src/serde.rs) with the optional `serde` feature.
Is this a feature that is out of scope for this crate or is there a chance it can be added?

**Comment by robclu** [comment]
Hey, I just had a look and it seems like it should be possible to add serde support. I will see if I can add that.

**Comment by robclu** [comment]
Hi,

I've added serde support for version 0.2.0. It required having the keys stored in the map, which were not there in the first version. It was quite a bit change which is why this took a while.

The tests for serde support are currently very simple, so if you run into any problems please submit an issue. It should be a lot faster to fix as the update to 0.2.0 was quite big in the end.

**Comment by mre** [comment]
Thanks a lot for adding this @robclu. I'll give it a try.
